# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-08 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hs_access_control', '0022_resourceaccess_require_download_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupGroupPrivilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege', models.IntegerField(choices=[(1, b'Owner'), (2, b'Change'), (3, b'View')], default=3, editable=False)),
                ('start', models.DateTimeField(auto_now=True)),
                ('grantor', models.ForeignKey(editable=False, help_text=b'grantor of privilege', on_delete=django.db.models.deletion.CASCADE, related_name='x2swp', to=settings.AUTH_USER_MODEL)),
                ('group_s', models.ForeignKey(editable=False, help_text=b'group providing privilege', on_delete=django.db.models.deletion.CASCADE, related_name='s2swp', to='auth.Group')),
                ('group_w', models.ForeignKey(editable=False, help_text=b'group to be granted privilege', on_delete=django.db.models.deletion.CASCADE, related_name='w2swp', to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupGroupProvenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege', models.IntegerField(choices=[(1, b'Owner'), (2, b'Change'), (3, b'View')], default=3, editable=False)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('undone', models.BooleanField(default=False, editable=False)),
                ('grantor', models.ForeignKey(editable=False, help_text=b'grantor of privilege', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='x2ghq', to=settings.AUTH_USER_MODEL)),
                ('group_s', models.ForeignKey(editable=False, help_text=b'group to which privilege applies', on_delete=django.db.models.deletion.CASCADE, related_name='h2ghq', to='auth.Group')),
                ('group_w', models.ForeignKey(editable=False, help_text=b'group to be granted privilege', on_delete=django.db.models.deletion.CASCADE, related_name='g2ghq', to='auth.Group')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='groupgroupprovenance',
            unique_together=set([('group_w', 'group_s', 'start')]),
        ),
        migrations.AlterUniqueTogether(
            name='groupgroupprivilege',
            unique_together=set([('group_w', 'group_s')]),
        ),
    ]
